### PR TITLE
Try to decompress crier records

### PR DESCRIPTION
**Pull request by regiskuckaertz**
See https://github.com/guardian/fastly-cache-purger/pull/8

- Tries to decompress the received record
- Falls back to normal deserialization if the former failed

### CODE REVIEW

**Review by alexduf — APPROVED** [review]
Looks fine to me @NathanielBennett you know this piece better, what do you think?

**Comment by regiskuckaertz** [comment]
Thanks @alexduf for your swift review 😗 I'll test in CODE to be sure.

**Comment by regiskuckaertz** [comment]
Argh, it failed to deploy with the following message: 
```
UPDATE_ROLLBACK_IN_PROGRESS The following resource(s) failed to update: [ExecutionRole]
```
any idea how to fix this?

**Comment by regiskuckaertz** [comment]
Tested in CODE and I can't see any error message:

screen shot 2018-12-03 at 17 09 37

Assuming this is fine? 🤗

**Comment by alexduf** [comment]
Yep all good, :shipit:

**Comment by regiskuckaertz** [comment]
Hmm, I think it does not work, I can't see logs after deserialisation 🤔 . Will investigate.

**Comment by regiskuckaertz** [comment]
YAY it worked
screen shot 2018-12-06 at 12 10 22

**Pull request merged**
